bw_blog_category:
    resource: "@BWBlogBundle/Resources/config/routing/category.yml"
    prefix:   /category

# added new homepage

bw_blog_post:
    resource: "@BWBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

# bw_blog_homepage:
#    path:     /hello/{name}/{status}
#     defaults: { _controller: BWBlogBundle:Default:index }

bw_blog_homepage:
    path:     /
    defaults: { _controller: BWBlogBundle:Default:index }

index:
    path:     /
    defaults: { _controller: BWBlogBundle:Default:index }


bw_blog_test_redirect:
    path:   /test_redirect
    defaults:
        _controller: BWBlogBundle:Default:testRedirect
    